-- Achievement support tables for Supabase/Postgres.
-- Run this once in Supabase SQL Editor.

-- Needed for First Follower and time-based social achievements.
alter table public.profiles
  add column if not exists created_at timestamptz not null default now();

-- One rating per user and episode.
create table if not exists public.episode_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  show_id bigint not null,
  episode_id bigint not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, episode_id)
);

-- Likes for comments/reviews.
create table if not exists public.comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id)
);

-- Saves of public custom lists by other users.
create table if not exists public.list_saves (
  id bigint generated by default as identity primary key,
  -- Stored as text because existing projects may use uuid or bigint for user_lists.id.
  list_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (list_id, user_id)
);

-- Explicit product/gameplay events that cannot be inferred from watched rows.
create table if not exists public.achievement_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in (
    'easter_egg_found',
    'profile_shared',
    'show_shared',
    'randomizer_completed',
    'chronological_completed',
    'advocacy_click'
  )),
  show_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Optional public saves/engagement counters can be queried efficiently.
create index if not exists episode_ratings_user_idx on public.episode_ratings(user_id);
create index if not exists episode_ratings_episode_idx on public.episode_ratings(episode_id);
create index if not exists comment_likes_comment_idx on public.comment_likes(comment_id);
create index if not exists comment_likes_user_idx on public.comment_likes(user_id);
create index if not exists list_saves_list_idx on public.list_saves(list_id);
create index if not exists list_saves_user_idx on public.list_saves(user_id);
create index if not exists achievement_events_user_type_idx on public.achievement_events(user_id, event_type);

-- Enable RLS.
alter table public.episode_ratings enable row level security;
alter table public.comment_likes enable row level security;
alter table public.list_saves enable row level security;
alter table public.achievement_events enable row level security;

-- Episode ratings: everyone can read, users manage their own rows.
drop policy if exists "episode ratings are publicly readable" on public.episode_ratings;
create policy "episode ratings are publicly readable"
  on public.episode_ratings for select using (true);
drop policy if exists "users manage own episode ratings" on public.episode_ratings;
create policy "users manage own episode ratings"
  on public.episode_ratings for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Comment likes: everyone can read, users manage their own likes.
drop policy if exists "comment likes are publicly readable" on public.comment_likes;
create policy "comment likes are publicly readable"
  on public.comment_likes for select using (true);
drop policy if exists "users manage own comment likes" on public.comment_likes;
create policy "users manage own comment likes"
  on public.comment_likes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- List saves: everyone can read, users manage their own saves.
drop policy if exists "list saves are publicly readable" on public.list_saves;
create policy "list saves are publicly readable"
  on public.list_saves for select using (true);
drop policy if exists "users manage own list saves" on public.list_saves;
create policy "users manage own list saves"
  on public.list_saves for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Achievement events: users can read and create only their own events.
drop policy if exists "users read own achievement events" on public.achievement_events;
create policy "users read own achievement events"
  on public.achievement_events for select using (auth.uid() = user_id);
drop policy if exists "users create own achievement events" on public.achievement_events;
create policy "users create own achievement events"
  on public.achievement_events for insert with check (auth.uid() = user_id);