-- =========================================================================
-- Migration: Create posts table for CMS / Blog System
-- Allows publishing articles, news, and official reviews.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL DEFAULT '',
  cover_image TEXT,
  author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  published BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Indices for high performance queries
CREATE INDEX IF NOT EXISTS idx_posts_slug ON public.posts (slug);
CREATE INDEX IF NOT EXISTS idx_posts_published_created_at ON public.posts (published, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_author_id ON public.posts (author_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- 1. Policy: Allow public read access to published posts
DROP POLICY IF EXISTS "Allow public read access to published posts" ON public.posts;
CREATE POLICY "Allow public read access to published posts"
  ON public.posts
  FOR SELECT
  TO public
  USING (published = true);

-- 2. Policy: Allow admins full access to posts (select, insert, update, delete)
DROP POLICY IF EXISTS "Allow admins full access to posts" ON public.posts;
CREATE POLICY "Allow admins full access to posts"
  ON public.posts
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 3. Policy: Allow service role full access to posts
DROP POLICY IF EXISTS "Allow service role full access to posts" ON public.posts;
CREATE POLICY "Allow service role full access to posts"
  ON public.posts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
