-- =========================================================================
-- Migration: Create site_settings table for Global Dynamic Text Management (CMS)
-- Allows updating static texts, titles, descriptions, and hero texts from Admin.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT NOT NULL UNIQUE,
  setting_value TEXT NOT NULL DEFAULT '',
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Index for fast lookup by key
CREATE INDEX IF NOT EXISTS idx_site_settings_key ON public.site_settings (setting_key);

-- Enable Row Level Security (RLS)
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- 1. Public Read Policy: Everyone (guest + users) can read site settings
DROP POLICY IF EXISTS "Allow public read access to site_settings" ON public.site_settings;
CREATE POLICY "Allow public read access to site_settings"
  ON public.site_settings
  FOR SELECT
  TO public
  USING (true);

-- 2. Admin Write Policy: Only authenticated users with role = 'admin' can insert/update/delete
DROP POLICY IF EXISTS "Allow admins full access to site_settings" ON public.site_settings;
CREATE POLICY "Allow admins full access to site_settings"
  ON public.site_settings
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 3. Service Role Policy: Full access for server-side management
DROP POLICY IF EXISTS "Allow service role full access to site_settings" ON public.site_settings;
CREATE POLICY "Allow service role full access to site_settings"
  ON public.site_settings
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Seed initial common settings for convenience
INSERT INTO public.site_settings (setting_key, setting_value, description)
VALUES 
  ('site_title', 'بینجر | دستیار هوشمند و ردیاب فیلم و سریال', 'عنوان تب مرورگر و عنوان اصلی سایت'),
  ('hero_title', 'جهان سینما در مشت شما؛ هوشمند و بی انتها', 'تیتر اصلی بالای صفحه اصلی و صفحه ورود'),
  ('hero_description', 'با ورود به بینجر، بیش از ۱۰,۰۰۰ سریال و فیلم را با هوش مصنوعی خلق‌کننده مود تماشا (Mood AI) و ردیابی اپیزودها تجربه کنید.', 'توضیحات معرفی زیر تیتر صفحه اصلی'),
  ('explore_page_title', 'اکسپلور و کشف هوشمند سریال‌ها', 'عنوان سربرگ صفحه اکسپلور'),
  ('critics_page_title', 'باشگاه منتقدان و دیدگاه‌های سینمایی', 'عنوان سربرگ صفحه منتقدان'),
  ('footer_copyright', 'تمامی حقوق مادی و معنوی برای پلتفرم بینجر محفوظ است.', 'متن کپی‌رایت انتهای فوتر')
ON CONFLICT (setting_key) DO NOTHING;
