-- =========================================================================
-- Migration: Create sms_logs table for SMS and OTP Delivery Monitoring
-- Stores outgoing SMS logs, delivery status, provider response & error messages
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.sms_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL,                              -- Recipient phone number (e.g., 09123456789)
  code TEXT,                                        -- OTP code (or masked code)
  status TEXT NOT NULL DEFAULT 'pending',           -- 'sent', 'failed', 'pending'
  provider TEXT NOT NULL DEFAULT 'melipayamak',     -- SMS Provider name
  rec_id TEXT,                                      -- Delivery / message ID returned by provider
  error_message TEXT,                               -- Error code or message if delivery failed
  ip_address TEXT,                                  -- Client IP address if available
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Indices for fast searching and filtering in Admin Panel
CREATE INDEX IF NOT EXISTS idx_sms_logs_phone ON public.sms_logs (phone);
CREATE INDEX IF NOT EXISTS idx_sms_logs_created_at ON public.sms_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sms_logs_status ON public.sms_logs (status);

-- Enable Row Level Security (RLS)
ALTER TABLE public.sms_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Allow admins to read sms logs
DROP POLICY IF EXISTS "Allow admins to read sms logs" ON public.sms_logs;
CREATE POLICY "Allow admins to read sms logs"
  ON public.sms_logs
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Policy: Allow service role full access to sms logs
DROP POLICY IF EXISTS "Allow service role full access to sms logs" ON public.sms_logs;
CREATE POLICY "Allow service role full access to sms logs"
  ON public.sms_logs
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
